---
title: "Compare GWAS results on the same trait from two versions of input data files"
author: "Xiang Zhu, Ph.D."
date: "First created on 2025-04-04; Last modified on `r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r, include=FALSE}
new_path <- "/Users/xiangzhu/Documents/1-Projects/hfpef/regenie/"
old_path <- "/Users/xiangzhu/Documents/3-Resources/SUMSTATS/diastolic2022/"
old_file <- "GCST90019012.h.tsv.gz"
```

## UKB-WGS

```{r, include=FALSE}
new_file <- "single_20250401_eur/hfpef_mri_single_20250401_eur_LAVI.regenie.gz"
```

```{r child=file.path(Sys.getenv("HOME"),"GitHub/hfpef/analysis/compare_previous_gwas.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.width=15, fig.height=5, fig.align='center',echo=FALSE}
print(new_plot)
print(old_plot)
```

## UKB-GEL

```{r, include=FALSE}
new_file <- "single_20250201_wbr/hfpef_mri_single_20250201_wbr_LAVI.regenie.gz"
```

```{r child=file.path(Sys.getenv("HOME"),"GitHub/hfpef/analysis/compare_previous_gwas.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.width=15, fig.height=5, fig.align='center',echo=FALSE}
print(new_plot)
print(old_plot)
```
