---
title: "Compare GWAS results on the same trait from two versions of input data files"
author: "Xiang Zhu, Ph.D."
date: "First created on 2025-04-04; Last modified on `r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r, include=FALSE}
dat_path <- "/Users/xiangzhu/Documents/1-Projects/brain2gene/regenie"
dis_path <- "single_2024_wbr"
dis_name <- "swi_median_20241122_wbr_IDP_SWI_T2star_right_thalamus.regenie.gz"
```

## WBR Single vs WBR Repeat I2

```{r, include=FALSE}
rep_path <- "i2_repeat_2024_wbr"
rep_name <- "swi_median_i2_repeat_20241122_wbr_IDP_SWI_T2star_right_thalamus.regenie.gz"
```

```{r child=file.path(Sys.getenv("HOME"),"GitHub/xzScripts/wflow_tpl/check_replication.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.width=15, fig.height=5, fig.align='center',echo=FALSE}
print(dis_plot)
rm(dis_plot)
```

## WBR Single vs WBR Repeat I3

```{r, include=FALSE}
rep_path <- "i3_repeat_2024_wbr"
rep_name <- "swi_median_i3_repeat_20241122_wbr_IDP_SWI_T2star_right_thalamus.regenie.gz"
```

```{r child=file.path(Sys.getenv("HOME"),"GitHub/xzScripts/wflow_tpl/check_replication.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.width=15, fig.height=5, fig.align='center',echo=FALSE}
print(dis_plot)
rm(dis_plot)
```

## WBR Single vs EMB Marginal I2

```{r, include=FALSE}
rep_path <- "i2_marginal_2024_emb"
rep_name <- "swi_median_i2_marginal_20241122_emb_IDP_SWI_T2star_right_thalamus.regenie.gz"
```

```{r child=file.path(Sys.getenv("HOME"),"GitHub/xzScripts/wflow_tpl/check_replication.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.width=15, fig.height=5, fig.align='center',echo=FALSE}
print(dis_plot)
rm(dis_plot)
```
