---
title: "Compare GWAS results on the same trait from two versions of input data files"
author: "Xiang Zhu, Ph.D."
date: "First created on 2025-04-04; Last modified on `r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r,include=FALSE}
old_file <- "/Users/xiangzhu/Documents/1-Projects/hfpef/regenie/single_20250201_wbr/hfpef_aba_single_20250201_wbr_aba_hfpef.regenie.gz"
my_range <- c(9, 35000001, 70000001)
```

## Step 1 SAK + Step 2 SAK + WGS PGEN

```{r, include=FALSE}
new_file <- "/Users/xiangzhu/Downloads/tmp/step1_sak_step2_sak/hfpef_aba_single_20250201_wbr_seg34_step2_aba_hfpef.regenie.gz"
```

### Summary of comparison

```{r child=file.path(Sys.getenv("HOME"),"GitHub/run-regenie/docs/compare_two_step2.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.align='center',echo=FALSE}
for (p in plot_ls) {
  print(p)
}
```

## Step 1 App + Step 2 SAK + WGS PGEN

```{r, include=FALSE}
new_file <- "/Users/xiangzhu/Downloads/tmp/step1_app_step2_sak/hfpef_aba_single_20250201_wbr_seg34_step2_aba_hfpef.regenie.gz"
```

### Summary of comparison

```{r child=file.path(Sys.getenv("HOME"),"GitHub/run-regenie/docs/compare_two_step2.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.align='center',echo=FALSE}
for (p in plot_ls) {
  print(p)
}
```

## Step 1 App + Step 2 APP + WGS BGEN

```{r, include=FALSE}
new_file <- "/Users/xiangzhu/Downloads/tmp/step1_app_step2_app/hfpef_aba_single_20250201_wbr_seg34_step2_aba_hfpef.regenie.gz"
```

### Summary of comparison

```{r child=file.path(Sys.getenv("HOME"),"GitHub/run-regenie/docs/compare_two_step2.Rmd"), echo=FALSE}
```

### Visualization of comparison

```{r, fig.align='center',echo=FALSE}
for (p in plot_ls) {
  print(p)
}
```
